// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"chat-app/config"
	"chat-app/internal/delivery/http"
	"chat-app/internal/delivery/middleware"
	"chat-app/internal/delivery/websocket"
	"chat-app/internal/repositories"
	"chat-app/internal/usecases"
	"chat-app/pkg/database"
	"chat-app/pkg/jwt"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, error) {
	jwtService := jwt.NewJWTService(cfg)
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := database.ConnectDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	messageRepository := repositories.NewMessageRepository(db)
	groupRepository := repositories.NewGroupRepository(db)
	messageUseCase := usecases.NewMessageUseCase(messageRepository, groupRepository)
	hub := websocket.NewHub(messageUseCase)
	authMiddleware := middleware.NewAuthMiddleware(jwtService)
	userRepository := repositories.NewUserRepository(db)
	authUseCase := usecases.NewAuthUseCase(userRepository, jwtService)
	authHandler := http.NewAuthHandler(authUseCase)
	userUseCase := usecases.NewUserUseCase(userRepository)
	userHandler := http.NewUserHandler(userUseCase)
	groupUseCase := usecases.NewGroupUseCase(groupRepository)
	groupHandler := http.NewGroupHandler(groupUseCase)
	app := NewApp(cfg, jwtService, hub, authMiddleware, authHandler, userHandler, groupHandler)
	return app, nil
}

// wire.go:

func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func provideJwtConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

var configSet = wire.NewSet(
	provideDatabaseConfig,
	provideJwtConfig,
)

var authSet = wire.NewSet(jwt.NewJWTService, usecases.NewAuthUseCase)

var middlewareSet = wire.NewSet(middleware.NewAuthMiddleware)

var repositorySet = wire.NewSet(repositories.NewUserRepository, repositories.NewGroupRepository, repositories.NewMessageRepository)

var usecaseSet = wire.NewSet(usecases.NewUserUseCase, usecases.NewMessageUseCase, usecases.NewGroupUseCase)

var handlerSet = wire.NewSet(http.NewUserHandler, http.NewAuthHandler, http.NewGroupHandler)

var webSocketSet = wire.NewSet(websocket.NewHub)
